# render.yaml
# Defines the infrastructure for the Currency Note Detector app

services:
  - type: web
    name: currency-detector
    env: python
    region: oregon # Change this to your preferred region (e.g., singapore)
    plan: free # Use 'starter' or higher for zero-downtime, non-sleeping services

    # 1. Configuration for the Build Phase
    buildCommand: |
      # Enforce a stable Python version known to work with NumPy/Pillow (e.g., 3.12)
      # If you keep Python 3.13, ensure your requirements.txt is updated as discussed.
      # If you are NOT using Python 3.13 on Render, you can omit the runtime.txt step.
      # For a dedicated version:
      # echo "python-3.12.3" > runtime.txt
      
      # Install dependencies from requirements.txt
      pip install -r requirements.txt
      
    # 2. Configuration for the Run Phase
    startCommand: gunicorn app:app
    
    # 3. Port Configuration
    # Render automatically uses the PORT environment variable, which Gunicorn binds to.
    
    # 4. Environment Variables (Critical for API Key)
    envVars:
      # Your API key must be secured as a secret environment variable.
      # This example uses the Perplexity key name. Change to GEMINI_API_KEY if needed.
      - key: PERPLEXITY_API_KEY
        sync: false
        # Set this value securely in the Render dashboard's "Secret Files" or "Environment Variables" section
        # DO NOT paste the actual key here if this file is public!
        value: # Placeholder for the key set in the dashboard
      
      # Set the Gunicorn bind address to allow external traffic
      - key: PORT
        value: 10000 # Render may override this, but good practice for gunicorn

    # 5. Continuous Deployment Settings
    autoDeploy: yes # Automatically deploy on every push to the main branch
    
    # 6. Health Check (Recommended for stability)
    healthCheckPath: /
